### ISSUE TITLE
你好，运行不出来是怎么回事

### ISSUE THREAD

**Issue by fengshaw1** [jinghuichen/Focused-Flip-Federated-Backdoor-Attack#3]
![image](https://github.com/jinghuichen/Focused-Flip-Federated-Backdoor-Attack/assets/57137032/c20446f5-5359-4313-9190-266ca3278243)
系统是windows10

**Comment by Greilfang** [comment]
你需要从{a1,a2,...}选择一个。

**Comment by fengshaw1** [comment]
懂了
